version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - backend-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "7000:7000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/graphqlAPI
      REDIS_URL: redis://redis:6379
      PORT: 7000
    depends_on:
      - mongodb
      - redis
    networks:
      - backend-network

volumes:
  mongo-data:

networks:
  backend-network:
